--Written by Tom Chmura
--small updates to USER_INFO and QUESTIONNAIRE tables by Lia Ferguson

-- Table: BUILDING_ACCESS
CREATE TABLE BUILDING_ACCESS(
Building_ID INT NOT NULL,
Building_time TIME NOT NULL,
User_ID INT NOT NULL,
FOREIGN KEY(User_ID) references USERS(User_ID));

-- Table: QUESTIONNAIRE
CREATE TABLE QUESTIONNAIRE(
User_ID INT NOT NULL,
Favorite_food VARCHAR(30),
Favorite_drink VARCHAR(30),
Favorite_hobby VARCHAR(30),
Allergies VARCHAR(30),
PRIMARY KEY(User_ID)
FOREIGN KEY(User_ID) references USERS(User_ID));

-- Table: USER_INFO
CREATE TABLE USER_INFO(
User_ID INT NOT NULL,
First_name VARCHAR(20) NOT NULL,
Last_name VARCHAR(20),
Superhero_Name VARCHAR(30),
PRIMARY KEY(User_ID)
FOREIGN KEY(User_ID) references USERS(User_ID));

-- Table: USERS
CREATE TABLE USERS(
User_ID INT NOT NULL,
Password VARCHAR(30) NOT NULL,
PRIMARY KEY(User_ID));

-- Table: PURCHASE_ORDERS
CREATE TABLE PURCHASE_ORDERS (
PO_NUMBER     INT          NOT NULL,
USER_ID       INT          NOT NULL,
ITEM          VARCHAR (30) NOT NULL,
COST          DOUBLE       NOT NULL,
TIME_RECEIVED TIME,
PRIMARY KEY (PO_NUMBER)
FOREIGN KEY(User_ID) references USERS(User_ID));
